export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_STUDENTS_STATISTICS_SUCCESS = 'LOAD_STUDENTS_STATISTICS_SUCCESS';
export const LOAD_STUDENTS_SUCCESS = 'LOAD_STUDENTS_SUCCESS';
export const COUNT_STUDENTS_SUCCCESS = 'COUNT_STUDENTS_SUCCCESS';
export const LOAD_STUDENT_SUCCESS = 'LOAD_STUDENT_SUCCESS';
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';

export const LOAD_ENROLLMENTS_SUCCESS = 'LOAD_ENROLLMENTS_SUCCESS';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_COURSE_SUCCESS = 'LOAD_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';

export const LOAD_INSTRUCTORS_SUCCESS = 'LOAD_INSTRUCTORS_SUCCESS';
export const LOAD_INSTRUCTOR_SUCCESS = 'LOAD_INSTRUCTOR_SUCCESS';
export const CREATE_INSTRUCTOR_SUCCESS = 'CREATE_INSTRUCTOR_SUCCESS';
export const UPDATE_INSTRUCTOR_SUCCESS = 'UPDATE_INSTRUCTOR_SUCCESS';
export const DELETE_INSTRUCTOR_SUCCESS = 'DELETE_INSTRUCTOR_SUCCESS';

export const LOAD_DEPARTMENTS_SUCCESS = 'LOAD_DEPARTMENTS_SUCCESS';
export const LOAD_DEPARTMENT_SUCCESS = 'LOAD_DEPARTMENT_SUCCESS';
export const CREATE_DEPARTMENT_SUCCESS = 'CREATE_DEPARTMENT_SUCCESS';
export const UPDATE_DEPARTMENT_SUCCESS = 'UPDATE_DEPARTMENT_SUCCESS';
export const DELETE_DEPARTMENT_SUCCESS = 'DELETE_DEPARTMENT_SUCCESS';

