export const LOAD_STUDENTS_STATISTICS = 'LOAD_STUDENTS_STATISTICS';
export const LOAD_STUDENTS = 'LOAD_STUDENTS';
export const COUNT_STUDENTS = 'COUNT_STUDENTS';
export const LOAD_STUDENT = 'LOAD_STUDENT';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const SEARCH_STUDENTS = 'SEARCH_STUDENTS';
export const CHANGE_SORT_ORDER = 'CHANGE_SORT_ORDER';

export const LOAD_COURSES = 'LOAD_COURSES';
export const LOAD_COURSE = 'LOAD_COURSE';
export const CHANGE_SELECTED_DEPARTMENT = 'CHANGE_SELECTED_DEPARTMENT';

export const LOAD_INSTRUCTORS = 'LOAD_INSTRUCTORS';
export const LOAD_INSTRUCTOR = 'LOAD_INSTRUCTOR';

export const LOAD_DEPARTMENTS = 'LOAD_DEPARTMENTS';
export const LOAD_DEPARTMENT = 'LOAD_DEPARTMENT';

export const LOAD_ENROLLMENTS = 'LOAD_ENROLLMENTS';
